using Wizards.Core.Model.WorldModels;
using Wizards.Core.Model.WorldModels.Enums;
using Wizards.Core.Model.WorldModels.Properties;
using Wizards.Repository.InitialData.SeedFactories.Interfaces;

namespace Wizards.Repository.InitialData.SeedFactories.Implementations;

public class InitialDataEnemiesFactory : IInitialDataEnemiesFactory
{
    public List<EnemyAttributes> GetEnemiesAttributes()
    {
        var result = new List<EnemyAttributes>();

        result.Add(new EnemyAttributes() { Id = 1, Damage = 10, Precision = 0, Specialization = 20, Defense = -10, Reflex = 20, MaxHealth = 200 });
        result.Add(new EnemyAttributes() { Id = 2, Damage = 10, Precision = 0, Specialization = 20, Defense = 20, Reflex = 0, MaxHealth = 200 });
        result.Add(new EnemyAttributes() { Id = 3, Damage = 15, Precision = 25, Specialization = 0, Defense = 25, Reflex = -7, MaxHealth = 250 });
        result.Add(new EnemyAttributes() { Id = 4, Damage = 15, Precision = 25, Specialization = 0, Defense = -10, Reflex = 25, MaxHealth = 275 });
        result.Add(new EnemyAttributes() { Id = 5, Damage = 1, Precision = 500, Specialization = 500, Defense = 50, Reflex = -100, MaxHealth = 100 });
        result.Add(new EnemyAttributes() { Id = 6, Damage = 20, Precision = 0, Specialization = 32, Defense = 25, Reflex = -7, MaxHealth = 400 });
        result.Add(new EnemyAttributes() { Id = 7, Damage = 20, Precision = 32, Specialization = 0, Defense = -10, Reflex = 25, MaxHealth = 400 });
        result.Add(new EnemyAttributes() { Id = 8, Damage = 25, Precision = 0, Specialization = 32, Defense = -15, Reflex = 28, MaxHealth = 450 });
        result.Add(new EnemyAttributes() { Id = 9, Damage = 25, Precision = 32, Specialization = -10, Defense = 28, Reflex = -7, MaxHealth = 450 });
        result.Add(new EnemyAttributes() { Id = 10, Damage = 1, Precision = 500, Specialization = 500, Defense = 50, Reflex = -100, MaxHealth = 200 });
        result.Add(new EnemyAttributes() { Id = 11, Damage = 30, Precision = 38, Specialization = 0, Defense = -15, Reflex = 32, MaxHealth = 750 });
        result.Add(new EnemyAttributes() { Id = 12, Damage = 30, Precision = 38, Specialization = 0, Defense = 32, Reflex = -5, MaxHealth = 750 });
        result.Add(new EnemyAttributes() { Id = 13, Damage = 35, Precision = 0, Specialization = 40, Defense = 35, Reflex = -7, MaxHealth = 1000 });
        result.Add(new EnemyAttributes() { Id = 14, Damage = 35, Precision = 0, Specialization = 42, Defense = -20, Reflex = 37, MaxHealth = 1200 });
        result.Add(new EnemyAttributes() { Id = 15, Damage = 1, Precision = 500, Specialization = 500, Defense = 50, Reflex = -100, MaxHealth = 300 });

        return result;
    }

    public List<EnemySkill> GetEnemiesSkills()
    {
        var result = new List<EnemySkill>();

        result.Add(new EnemySkill() { Id = 1, EnemyId = 1, Name = "Stroke", Type = EnemySkillType.Attack, DamageFactor = 0.28d, BaseHitChance = 80, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 2, EnemyId = 1, Name = "Cutting Axe", Type = EnemySkillType.StrongAttack, DamageFactor = 0.48d, BaseHitChance = 95, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 3, EnemyId = 1, Name = "Impact", Type = EnemySkillType.Attack, DamageFactor = 0.38d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 4, EnemyId = 1, Name = "Cruel Smash", Type = EnemySkillType.StrongAttack, DamageFactor = 0.59d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 5, EnemyId = 2, Name = "Smash", Type = EnemySkillType.Attack, DamageFactor = 0.39d, BaseHitChance = 70, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 6, EnemyId = 2, Name = "Break Bones", Type = EnemySkillType.StrongAttack, DamageFactor = 0.74d, BaseHitChance = 85, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 7, EnemyId = 2, Name = "Mace hit", Type = EnemySkillType.Attack, DamageFactor = 0.48d, BaseHitChance = 75, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 8, EnemyId = 2, Name = "Destructive lash", Type = EnemySkillType.StrongAttack, DamageFactor = 0.95d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 9, EnemyId = 3, Name = "Quick Shot", Type = EnemySkillType.Attack, DamageFactor = 0.3d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 10, EnemyId = 3, Name = "Double Arrow", Type = EnemySkillType.StrongAttack, DamageFactor = 0.54d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 11, EnemyId = 3, Name = "Sneaky Shot", Type = EnemySkillType.Attack, DamageFactor = 0.4d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 12, EnemyId = 3, Name = "Perfect Arrow", Type = EnemySkillType.StrongAttack, DamageFactor = 0.75d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 13, EnemyId = 4, Name = "Peck", Type = EnemySkillType.Attack, DamageFactor = 0.39d, BaseHitChance = 95, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 14, EnemyId = 4, Name = "Cutting Claw", Type = EnemySkillType.StrongAttack, DamageFactor = 0.6d, BaseHitChance = 85, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 15, EnemyId = 4, Name = "Dangerous Beak", Type = EnemySkillType.StrongAttack, DamageFactor = 0.82d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 16, EnemyId = 4, Name = "Scratch", Type = EnemySkillType.Attack, DamageFactor = 0.47d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 17, EnemyId = 4, Name = "Bloody Claws", Type = EnemySkillType.StrongAttack, DamageFactor = 0.95d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 18, EnemyId = 4, Name = "Triple Scratch", Type = EnemySkillType.StrongAttack, DamageFactor = 1.41d, BaseHitChance = 105, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 19, EnemyId = 5, Name = "Simple Attack [pattern I]", Type = EnemySkillType.Attack, DamageFactor = 1d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 20, EnemyId = 5, Name = "Strong Attack [pattern I]", Type = EnemySkillType.StrongAttack, DamageFactor = 4d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 21, EnemyId = 5, Name = "Simple Attack [pattern II]", Type = EnemySkillType.Attack, DamageFactor = 2d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 22, EnemyId = 5, Name = "Strong Attack [pattern II]", Type = EnemySkillType.StrongAttack, DamageFactor = 9d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 23, EnemyId = 6, Name = "Mace strike", Type = EnemySkillType.Attack, DamageFactor = 0.34d, BaseHitChance = 80, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 24, EnemyId = 6, Name = "Cruel Hit", Type = EnemySkillType.StrongAttack, DamageFactor = 0.72d, BaseHitChance = 90, ArmorPenetrationPercent = 12, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 25, EnemyId = 6, Name = "Simple Slug", Type = EnemySkillType.Attack, DamageFactor = 0.37d, BaseHitChance = 85, ArmorPenetrationPercent = 8, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 26, EnemyId = 6, Name = "Agonized Mace Strike", Type = EnemySkillType.StrongAttack, DamageFactor = 0.87d, BaseHitChance = 100, ArmorPenetrationPercent = 12, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 27, EnemyId = 6, Name = "Shocking Strike", Type = EnemySkillType.Stunning, DamageFactor = 0.2d, BaseHitChance = 122, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 28, EnemyId = 7, Name = "Quick Bite", Type = EnemySkillType.Attack, DamageFactor = 0.42d, BaseHitChance = 105, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 29, EnemyId = 7, Name = "Triple Bite", Type = EnemySkillType.StrongAttack, DamageFactor = 0.76d, BaseHitChance = 99, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 30, EnemyId = 7, Name = "Precise Scratch", Type = EnemySkillType.Attack, DamageFactor = 0.48d, BaseHitChance = 109, ArmorPenetrationPercent = -2, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 31, EnemyId = 7, Name = "Harmful Fangs", Type = EnemySkillType.StrongAttack, DamageFactor = 0.92d, BaseHitChance = 94, ArmorPenetrationPercent = -1, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 32, EnemyId = 7, Name = "Devouring Howl", Type = EnemySkillType.Stunning, DamageFactor = 0.33d, BaseHitChance = 120, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 33, EnemyId = 8, Name = "Branch Strike", Type = EnemySkillType.Attack, DamageFactor = 0.38d, BaseHitChance = 95, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 34, EnemyId = 8, Name = "Fury Stalks", Type = EnemySkillType.StrongAttack, DamageFactor = 0.68d, BaseHitChance = 90, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 35, EnemyId = 8, Name = "Striking Vines", Type = EnemySkillType.Attack, DamageFactor = 0.41d, BaseHitChance = 90, ArmorPenetrationPercent = 5, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 36, EnemyId = 8, Name = "Whirling Sprouts", Type = EnemySkillType.StrongAttack, DamageFactor = 0.84d, BaseHitChance = 85, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 37, EnemyId = 8, Name = "Entangle", Type = EnemySkillType.Stunning, DamageFactor = 0.26d, BaseHitChance = 130, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 38, EnemyId = 9, Name = "Smashing Tail", Type = EnemySkillType.Attack, DamageFactor = 0.42d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 39, EnemyId = 9, Name = "Lions Bite", Type = EnemySkillType.StrongAttack, DamageFactor = 0.9d, BaseHitChance = 105, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 40, EnemyId = 9, Name = "Sneaky Tail Bait", Type = EnemySkillType.Attack, DamageFactor = 0.5d, BaseHitChance = 95, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 41, EnemyId = 9, Name = "Flame Breath", Type = EnemySkillType.StrongAttack, DamageFactor = 1.18d, BaseHitChance = 110, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 42, EnemyId = 9, Name = "Poisoned Teeth", Type = EnemySkillType.Stunning, DamageFactor = 0.64d, BaseHitChance = 130, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 43, EnemyId = 10, Name = "Simple Attack [pattern I]", Type = EnemySkillType.Attack, DamageFactor = 4d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 44, EnemyId = 10, Name = "Stunning Attack [pattern I]", Type = EnemySkillType.Stunning, DamageFactor = 2d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 45, EnemyId = 10, Name = "Strong Attack [pattern I]", Type = EnemySkillType.StrongAttack, DamageFactor = 7d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 46, EnemyId = 11, Name = "Scratch", Type = EnemySkillType.Attack, DamageFactor = 0.51d, BaseHitChance = 95, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 47, EnemyId = 11, Name = "Vampire Bait", Type = EnemySkillType.StrongAttack, DamageFactor = 1.37d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 48, EnemyId = 11, Name = "Wing Slap", Type = EnemySkillType.Attack, DamageFactor = 0.57d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 49, EnemyId = 11, Name = "Dangerous Claws", Type = EnemySkillType.StrongAttack, DamageFactor = 1.46d, BaseHitChance = 105, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 50, EnemyId = 11, Name = "Cutting Clutches", Type = EnemySkillType.Attack, DamageFactor = 0.61d, BaseHitChance = 85, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 51, EnemyId = 11, Name = "Puncturing Sting", Type = EnemySkillType.StrongAttack, DamageFactor = 1.92d, BaseHitChance = 120, ArmorPenetrationPercent = 5, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 52, EnemyId = 11, Name = "Hypnosis", Type = EnemySkillType.Stunning, DamageFactor = 0.45d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 53, EnemyId = 11, Name = "Whirling Wings", Type = EnemySkillType.Charge, DamageFactor = 1.14d, BaseHitChance = 90, ArmorPenetrationPercent = 5, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 54, EnemyId = 12, Name = "Dark Blade", Type = EnemySkillType.Attack, DamageFactor = 0.53d, BaseHitChance = 90, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 55, EnemyId = 12, Name = "Demonic Curse", Type = EnemySkillType.StrongAttack, DamageFactor = 1.46d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 56, EnemyId = 12, Name = "Hunting Daggers", Type = EnemySkillType.Attack, DamageFactor = 0.61d, BaseHitChance = 95, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 57, EnemyId = 12, Name = "Mind Ripping ", Type = EnemySkillType.StrongAttack, DamageFactor = 1.85d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 58, EnemyId = 12, Name = "Cutting Darkness", Type = EnemySkillType.Attack, DamageFactor = 0.67d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 59, EnemyId = 12, Name = "Soul Devastation", Type = EnemySkillType.StrongAttack, DamageFactor = 2.12d, BaseHitChance = 105, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 60, EnemyId = 12, Name = "Possession", Type = EnemySkillType.Stunning, DamageFactor = 0.51d, BaseHitChance = 130, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 61, EnemyId = 12, Name = "Demon's Rush", Type = EnemySkillType.Charge, DamageFactor = 1.2d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 62, EnemyId = 13, Name = "Spike", Type = EnemySkillType.Attack, DamageFactor = 0.49d, BaseHitChance = 85, ArmorPenetrationPercent = 5, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 63, EnemyId = 13, Name = "Deep Stab", Type = EnemySkillType.StrongAttack, DamageFactor = 1.18d, BaseHitChance = 90, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 64, EnemyId = 13, Name = "Dark Knife", Type = EnemySkillType.Attack, DamageFactor = 0.51d, BaseHitChance = 80, ArmorPenetrationPercent = 5, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 65, EnemyId = 13, Name = "Clapper Claw", Type = EnemySkillType.StrongAttack, DamageFactor = 1.21d, BaseHitChance = 85, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 66, EnemyId = 13, Name = "Maul", Type = EnemySkillType.Attack, DamageFactor = 0.55d, BaseHitChance = 78, ArmorPenetrationPercent = 5, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 67, EnemyId = 13, Name = "Cleaving Fangs", Type = EnemySkillType.StrongAttack, DamageFactor = 1.33d, BaseHitChance = 87, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 68, EnemyId = 13, Name = "Shivering Howl", Type = EnemySkillType.Stunning, DamageFactor = 0.33d, BaseHitChance = 100, ArmorPenetrationPercent = -3, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 69, EnemyId = 13, Name = "Rushing Fury", Type = EnemySkillType.Charge, DamageFactor = 0.91d, BaseHitChance = 133, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 70, EnemyId = 14, Name = "Bite", Type = EnemySkillType.Attack, DamageFactor = 0.51d, BaseHitChance = 100, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 71, EnemyId = 14, Name = "Strong Jaws", Type = EnemySkillType.StrongAttack, DamageFactor = 0.91d, BaseHitChance = 120, ArmorPenetrationPercent = 12, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 72, EnemyId = 14, Name = "Legs Beating", Type = EnemySkillType.Attack, DamageFactor = 0.55d, BaseHitChance = 95, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 73, EnemyId = 14, Name = "Deep Sting", Type = EnemySkillType.StrongAttack, DamageFactor = 0.99d, BaseHitChance = 130, ArmorPenetrationPercent = 12, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 74, EnemyId = 14, Name = "Wounding cut", Type = EnemySkillType.Attack, DamageFactor = 0.57d, BaseHitChance = 85, ArmorPenetrationPercent = 10, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 75, EnemyId = 14, Name = "Trample", Type = EnemySkillType.StrongAttack, DamageFactor = 1.05d, BaseHitChance = 80, ArmorPenetrationPercent = 12, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 76, EnemyId = 14, Name = "Spiderweb", Type = EnemySkillType.Stunning, DamageFactor = 0.33d, BaseHitChance = 140, ArmorPenetrationPercent = 12, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 77, EnemyId = 14, Name = "Spider Stomp", Type = EnemySkillType.Charge, DamageFactor = 0.77d, BaseHitChance = 160, ArmorPenetrationPercent = 15, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 78, EnemyId = 15, Name = "Simple Attack", Type = EnemySkillType.Attack, DamageFactor = 9d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 79, EnemyId = 15, Name = "Strong Attack", Type = EnemySkillType.StrongAttack, DamageFactor = 27d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });
        result.Add(new EnemySkill() { Id = 80, EnemyId = 15, Name = "Charge", Type = EnemySkillType.Charge, DamageFactor = 18d, BaseHitChance = 100, ArmorPenetrationPercent = 0, HealingFactor = 0 });

        return result;
    }

    public List<BehaviorPattern> GetEnemiesBehaviorPatterns()
    {
        var result = new List<BehaviorPattern>();

        result.Add(new BehaviorPattern() { Id = 1, EnemyId = 1, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 1 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 1 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 2 } } });
        result.Add(new BehaviorPattern() { Id = 2, EnemyId = 1, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 3 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 3 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 4 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 3 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 4 } } });
        result.Add(new BehaviorPattern() { Id = 3, EnemyId = 2, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 5 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 5 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 5 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 6 } } });
        result.Add(new BehaviorPattern() { Id = 4, EnemyId = 2, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 7 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 7 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 8 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 7 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 8 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 7 } } });
        result.Add(new BehaviorPattern() { Id = 5, EnemyId = 3, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 9 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 9 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 9 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 10 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 9 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 10 } } });
        result.Add(new BehaviorPattern() { Id = 6, EnemyId = 3, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 11 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 12 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 11 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 11 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 12 } } });
        result.Add(new BehaviorPattern() { Id = 7, EnemyId = 4, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 13 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 13 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 14 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 13 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 13 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 15 } } });
        result.Add(new BehaviorPattern() { Id = 8, EnemyId = 4, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 16 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 16 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 17 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 16 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 18 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 16 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 18 } } });
        result.Add(new BehaviorPattern() { Id = 9, EnemyId = 5, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 19 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 19 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 20 } } });
        result.Add(new BehaviorPattern() { Id = 10, EnemyId = 5, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 21 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 21 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 21 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 22 } } });
        result.Add(new BehaviorPattern() { Id = 11, EnemyId = 6, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 23 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 23 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 23 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 24 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 23 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 27 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 24 } } });
        result.Add(new BehaviorPattern() { Id = 12, EnemyId = 6, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 25 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 25 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 26 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 25 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 25 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 25 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 27 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 26 } } });
        result.Add(new BehaviorPattern() { Id = 13, EnemyId = 7, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 28 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 29 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 28 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 28 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 28 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 32 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 28 } } });
        result.Add(new BehaviorPattern() { Id = 14, EnemyId = 7, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 30 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 30 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 30 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 31 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 30 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 30 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 32 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 31 } } });
        result.Add(new BehaviorPattern() { Id = 15, EnemyId = 8, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 33 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 33 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 37 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 33 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 33 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 34 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 33 } } });
        result.Add(new BehaviorPattern() { Id = 16, EnemyId = 8, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 35 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 35 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 35 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 37 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 36 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 35 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 37 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 35 } } });
        result.Add(new BehaviorPattern() { Id = 17, EnemyId = 9, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 38 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 38 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 38 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 39 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 38 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 38 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 42 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 38 }, new SkillSequenceStep() { SequenceStepId = 9, SkillId = 42 }, new SkillSequenceStep() { SequenceStepId = 10, SkillId = 39 } } });
        result.Add(new BehaviorPattern() { Id = 18, EnemyId = 9, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 40 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 40 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 40 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 42 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 41 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 40 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 40 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 42 }, new SkillSequenceStep() { SequenceStepId = 9, SkillId = 40 }, new SkillSequenceStep() { SequenceStepId = 10, SkillId = 42 }, new SkillSequenceStep() { SequenceStepId = 11, SkillId = 41 } } });
        result.Add(new BehaviorPattern() { Id = 19, EnemyId = 10, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 43 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 45 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 44 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 45 } } });
        result.Add(new BehaviorPattern() { Id = 20, EnemyId = 11, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 66, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 46 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 46 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 47 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 46 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 52 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 47 } } });
        result.Add(new BehaviorPattern() { Id = 21, EnemyId = 11, MaxHealthPercentToTrigger = 66, MinHealthPercentToTrigger = 33, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 48 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 48 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 49 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 53 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 49 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 46 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 46 } } });
        result.Add(new BehaviorPattern() { Id = 22, EnemyId = 11, MaxHealthPercentToTrigger = 33, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 50 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 48 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 48 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 53 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 51 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 50 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 48 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 49 } } });
        result.Add(new BehaviorPattern() { Id = 23, EnemyId = 12, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 66, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 54 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 61 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 55 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 54 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 54 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 55 } } });
        result.Add(new BehaviorPattern() { Id = 24, EnemyId = 12, MaxHealthPercentToTrigger = 66, MinHealthPercentToTrigger = 33, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 56 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 56 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 57 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 54 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 56 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 60 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 57 } } });
        result.Add(new BehaviorPattern() { Id = 25, EnemyId = 12, MaxHealthPercentToTrigger = 33, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 58 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 56 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 61 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 58 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 56 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 58 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 61 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 59 } } });
        result.Add(new BehaviorPattern() { Id = 26, EnemyId = 13, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 66, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 62 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 62 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 63 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 62 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 62 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 69 } } });
        result.Add(new BehaviorPattern() { Id = 27, EnemyId = 13, MaxHealthPercentToTrigger = 66, MinHealthPercentToTrigger = 33, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 64 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 65 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 62 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 64 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 64 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 68 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 62 } } });
        result.Add(new BehaviorPattern() { Id = 28, EnemyId = 13, MaxHealthPercentToTrigger = 33, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 66 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 69 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 67 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 64 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 66 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 69 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 68 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 67 } } });
        result.Add(new BehaviorPattern() { Id = 29, EnemyId = 14, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 75, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 77 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 71 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 70 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 70 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 76 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 71 } } });
        result.Add(new BehaviorPattern() { Id = 30, EnemyId = 14, MaxHealthPercentToTrigger = 75, MinHealthPercentToTrigger = 50, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 72 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 72 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 73 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 72 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 70 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 76 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 73 } } });
        result.Add(new BehaviorPattern() { Id = 31, EnemyId = 14, MaxHealthPercentToTrigger = 50, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 74 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 77 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 75 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 72 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 76 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 75 }, new SkillSequenceStep() { SequenceStepId = 7, SkillId = 77 }, new SkillSequenceStep() { SequenceStepId = 8, SkillId = 76 }, new SkillSequenceStep() { SequenceStepId = 9, SkillId = 75 }, new SkillSequenceStep() { SequenceStepId = 10, SkillId = 72 }, new SkillSequenceStep() { SequenceStepId = 11, SkillId = 74 } } });
        result.Add(new BehaviorPattern() { Id = 32, EnemyId = 15, MaxHealthPercentToTrigger = 100, MinHealthPercentToTrigger = 0, SequenceOfSkillsId = new List<SkillSequenceStep>() { new SkillSequenceStep() { SequenceStepId = 1, SkillId = 78 }, new SkillSequenceStep() { SequenceStepId = 2, SkillId = 78 }, new SkillSequenceStep() { SequenceStepId = 3, SkillId = 79 }, new SkillSequenceStep() { SequenceStepId = 4, SkillId = 78 }, new SkillSequenceStep() { SequenceStepId = 5, SkillId = 80 }, new SkillSequenceStep() { SequenceStepId = 6, SkillId = 79 } } });

        return result;
    }

    public List<Enemy> GetEnemies()
    {
        var result = new List<Enemy>();

        result.Add(new Enemy() { Id = 1, AttributesId = 1, AvatarImageNumber = 11, Name = "Minotaur", Description = "Minotaur is great fighter. His attacks can easly overpass your armor, but are also very slow, so it will be easy to avoid them with some reflex. Minotaur also has some reflex so it is not easy to hit him. This enemy is vulnerable to damage because of his weak armor. Minotaur has dangerous Strong attacks so you should block them as often as you can.", EnemyStageName = "Great Forest of Anumer", GoldReward = 5, RankPointsReward = 5, StageBackgroundImageNumber = 11, Tier = 1, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 2, AttributesId = 2, AvatarImageNumber = 12, Name = "Cyclopus", Description = "This enemy is very slow with his attacks, so with some reflex it will be easy to avoid them. His attacks can easly overpass your armor. Cyclopus is specialized in defense. If you want to deal him lot of damage, you have to maximize your specialization to oveprass his armor. This enemy also has Strong attacks; beware them if you want to keep your healt high.", EnemyStageName = "Lonely Island", GoldReward = 10, RankPointsReward = 5, StageBackgroundImageNumber = 12, Tier = 1, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 3, AttributesId = 3, AvatarImageNumber = 13, Name = "Utmar Sneaky Hoof", Description = "Centarus are great archers. They can easly hit you with his attacks and deals you a lot of damage. The point is to maximize your defense instead of trying to avoid attacs. Utmar is very precise but has not good enough reflex. He has also high defense ability. To be more effective take some specialization for higher damage. You will need Blocking skill to protect yourself from his Strong Attacks", EnemyStageName = "Ruins of Verath", GoldReward = 15, RankPointsReward = 10, StageBackgroundImageNumber = 13, Tier = 1, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 4, AttributesId = 4, AvatarImageNumber = 14, Name = "Overis The Griffon Warrior", Description = "Griffon is super precise enemy. It is quite impossible to avoid thiers attacks which are also dangerous. If you want to survive battle with him you need as much defense as you can take. Overis has good reflex so it is not easy to hit him. To be more effective fighter you should keep your precision high. That will help you defeat this enemy. Griffon has some Strong Attacks that will deal you very high damage, so good blocking will be the best strategy.", EnemyStageName = "Griffon Nest in Leven Highlands", GoldReward = 20, RankPointsReward = 15, StageBackgroundImageNumber = 14, Tier = 1, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 5, AttributesId = 5, AvatarImageNumber = 61, Name = "Training Manequin T1 Mechanics", Description = "This is Training Manequin that shows Strong Attacks and Attack Patterns. Attack Patterns are sequence of skill that boss is repeating. Patterns depends on Enemy's Health percent. Enemies can have up to four diffrent patterns (depends on enemy's tier). This Manequin demonstrate two sequences: First (100%-50%) - two simple attacks with 1 damage and one strong attack with 4 damage; Second (50% - 0%) - three simple attacks with 2 damage and one strong attack with 10 damage. When boss has prepared Strong Attack for round there will be orange icon above his card that signalizes this mechanic. Strong Attacks can be blocked by your Block skill. Start match with this manequin to get safely expirience about this basic Tier 1 mechanics.", EnemyStageName = "Training Grounds", GoldReward = 0, RankPointsReward = 0, StageBackgroundImageNumber = 61, Tier = 1, Type = EnemyType.Boss, TrainingEnemy = true });
        result.Add(new Enemy() { Id = 6, AttributesId = 6, AvatarImageNumber = 21, Name = "Malaur - Ettin King", Description = "Ettins are known for its strong attacks that crashes armor. Luckly most of Ettins Attacks are easy to avoid if you have enought reflex. Malaures is very slow enemy so it is not hard to succesfully hit him during combat. His thick skin protect him well so to be effective, you will bring Specialization to the fight. This enemy can stun you with one of its special attacks. Beware of it and block it because Ettins like to stun theirs enemies and than land Strong Attack on them without much effort.", EnemyStageName = "Old Temple in Caladhorn Wilds", GoldReward = 20, RankPointsReward = 20, StageBackgroundImageNumber = 21, Tier = 2, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 7, AttributesId = 7, AvatarImageNumber = 22, Name = "Cerberus", Description = "Very quick and precise enemy. Its not so easy to avoid his attacks and succesfully hit him. Reflex would be useless during fight but defense will help to reduce damage. Cerberus is very vulnerable to damage so there is no need for specialization. Cerberus can prepare Terrifying Howl thats will stuns you. It would be better to perfectly Block this attack because Cerberus is much more dangerous when you are Stunned.", EnemyStageName = "Gallen-Tum Watchtower", GoldReward = 25, RankPointsReward = 20, StageBackgroundImageNumber = 22, Tier = 2, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 8, AttributesId = 8, AvatarImageNumber = 23, Name = "Volantur", Description = "Volantur is the Ent King. He is very specialized warrior. His attacks are very dangerous because of high damage and high armor overpassing. To survive tha battle with him you will need reflex to avoid his attacks as often as you can. Volantur is also very quick enemy. to successfully hit him you will need a lot of precision. As a King of Trees and Vines he can Entangle you with one of his abilities that causes Stun. Make shure to Block this attack when its incomeing. Volantur is known for his cruel strategy. He likes Stuns enemies and then hit them with Strong attacks when they cannot move. Beware of it.", EnemyStageName = "Sorrow Wetlands", GoldReward = 30, RankPointsReward = 25, StageBackgroundImageNumber = 23, Tier = 2, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 9, AttributesId = 9, AvatarImageNumber = 24, Name = "Chimera", Description = "One of the most dangerous enemies. Its atacks are very precise and it is quite impossible to avoid them. Luckly damage of its atacks can be easily reduced by defense. Instead of avoiding attacks Chimera has high defense to protect itself. To conquer it effectively you should maximize your specialization. Chimeras tail is double dangerous, because it can hit very hard and also has sneak head that can bite you with Poisoned Teeth's. It would cause you to be Stunned for one round. You have to watch carefully its behavior and block this stunning attack, because after it chimera can easily hit you very strong.", EnemyStageName = "Forsaken Morath Caverns", GoldReward = 35, RankPointsReward = 30, StageBackgroundImageNumber = 24, Tier = 2, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 10, AttributesId = 10, AvatarImageNumber = 61, Name = "Training Manequin T2 Mechanics", Description = "This is Training Manequin that shows Stunning Attacks. Stunning Attacks, when hits, will make you unable to action in next round. This is dangerous mechanic because when you are stunned the damage you takes are much higher, and enemy cannot miss attack on you (no matter how high is your reflex). Thats why it is very important to use Block skill from your skill bar to block Stunning Attacks. This manequin has special Attacks Pattern as follows: 1x Simple Attack (4 dmg), 1x Strong Attack (8 dmg), 1x Stunning Attack (2 dmg and make you stunn), 1x Strong Attack (8 dmg - if you are not Stunned; 16 dmg if you are Stunned;). When boss has prepared Stunning Attack for round there will be violet icon with blac spiral above his card that signalizes this mechanic. Start match with this manequin to get safely expirience about this Tier 2 new mechanics.", EnemyStageName = "Training Grounds", GoldReward = 0, RankPointsReward = 0, StageBackgroundImageNumber = 61, Tier = 2, Type = EnemyType.Boss, TrainingEnemy = true });
        result.Add(new Enemy() { Id = 11, AttributesId = 11, AvatarImageNumber = 31, Name = "Harpy", Description = "Harpies are sneaky enemies with very high precision and perfect ability to avoid attacks. Besides theirs Strong Attacks she can Hypnotize you that makes you Stunned for next round. But the most dangerous is charge attack, because it also makes you Stunned for one round. Remember that when you are stunned you will take much more damage from enemy attacks. But if you counters she's charge, Harpy would be vulnerable to damage and there is no way to miss her so it is important to take chance of it and damage down her faster. ", EnemyStageName = "Old Mountain Grotto", GoldReward = 50, RankPointsReward = 45, StageBackgroundImageNumber = 31, Tier = 3, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 12, AttributesId = 12, AvatarImageNumber = 32, Name = "Saveriaxen", Description = "Legendary Demon with high defense and super precised attacks. He has ability to Posses enemies what makes them stunned. Sevariaxen has many dangerous strong attacks and many of them occurs directly after his Stunning abilities. So beware of his Charge, but if you counter it that will make Deamon Stunned for one round and you will deal him much more damage and easily hit him. Dont underestimate his strong attacks and stunning skills because of high damage they deals. If you equipp yourself with proper gear and lern countering enemy charge, you will have chance to beat him. ", EnemyStageName = "Crimson Garden", GoldReward = 100, RankPointsReward = 55, StageBackgroundImageNumber = 32, Tier = 3, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 13, AttributesId = 13, AvatarImageNumber = 33, Name = "Luperius", Description = "Great Champion of Werewolfs. His thick skin protects him very well from damage. His claws ar really hard and sharp so he can easily overpass your defense. Luperius is great warrior that fight till end, and when his healt is getting lower he will be much more dangerous. In his Fury he can rush on you and make you stunned. This is how he charges on theirs enemies. Luperius is dangerous enemy so you have to pay attention of his attacks and prepare yourself well before fight. If you take your opportunity to counter his charge attack he will be stunned and you will have one round to deal as much damage as you can without any risk that you miss attack. ", EnemyStageName = "Darken Woodlands", GoldReward = 150, RankPointsReward = 65, StageBackgroundImageNumber = 33, Tier = 3, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 14, AttributesId = 14, AvatarImageNumber = 34, Name = "Arganthula", Description = "The great legendary spider queen is the most filthy incarnation of all fears. She is very quick so easily can avoid your attacks. Furthermore Arganthula's attacks are so strong that even high defense will not help to reduce them. The only chance you have is maximize your reflex to avoid them which is not so easy. She likes Spiderwebs which can stunn you as she's annother dangerous mechanic - Charge attack. To beat this abomination of nature you should prepare yourself really well with gear and tacticks. The fight will be long and will need your focus. One single mistake may be your last. Beware!", EnemyStageName = "Lair of Legendary Spider Queen", GoldReward = 150, RankPointsReward = 75, StageBackgroundImageNumber = 34, Tier = 3, Type = EnemyType.Boss, TrainingEnemy = false });
        result.Add(new Enemy() { Id = 15, AttributesId = 15, AvatarImageNumber = 61, Name = "Training Manequin T3 Mechanics", Description = "This is Tier 3 Training Mannequin. He Shows how works new special mechanic on Tier 3 bosses - Charge attack. Charge attack is another boss attack that can stunn you. There is a difference between Stunning and Charge. Charge attack cannot be blocked by your Block Skill, it needs to be countered by you Counter Attack skill. Charge attacks are signalized by blue icon above enemy's card. If you don't counter Charge attack you will be Stunned fo next round and you will take a lot of damage from next Boss attack in his Pattern that will never misshits you. But if you counter Enemy Charge attack you will make the Boss Stunned! Stunned enemy also takes a lot of damage, you cannot misshits him and he will not able to perform his next skill. That's why countering Charge attack is so important. Many of Enemies has a lot of Health ant this is perfect chance to cast the most powerfull attacks on them to easily win fight!", EnemyStageName = "Training Grounds", GoldReward = 0, RankPointsReward = 0, StageBackgroundImageNumber = 61, Tier = 3, Type = EnemyType.Boss, TrainingEnemy = true });

        return result;
    }
}