using Wizards.Core.Model;
using Wizards.Core.Model.Enums;
using Wizards.Core.Model.Properties;
using Wizards.Repository.InitialData.SeedFactories.Interfaces;

namespace Wizards.Repository.InitialData.SeedFactories.Implementations;

public class InitialDataHeroesFactory : IInitialDataHeroesFactory
{
    public List<Hero> GetHeroes()
    {
        var result = new List<Hero>();
        var rnd = new Random(DateTime.Now.Millisecond);

        // Random Data for testing functionalists
        result.Add(new Hero { PlayerId = 6, NickName = "Gelantres", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 38536, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 7926, TotalMatchPlayed = 793, TotalMatchLoose = 462, TotalMatchWin = 331 } });
        result.Add(new Hero { PlayerId = 7, NickName = "Morion", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 11347, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 115727, TotalMatchPlayed = 11573, TotalMatchLoose = 7750, TotalMatchWin = 3823 } });
        result.Add(new Hero { PlayerId = 8, NickName = "Durian Twardy", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 13544, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 106126, TotalMatchPlayed = 10613, TotalMatchLoose = 4615, TotalMatchWin = 5998 } });
        result.Add(new Hero { PlayerId = 9, NickName = "Lathron", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 28194, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 115359, TotalMatchPlayed = 11536, TotalMatchLoose = 5801, TotalMatchWin = 5735 } });
        result.Add(new Hero { PlayerId = 10, NickName = "Gajard", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 4326, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 78840, TotalMatchPlayed = 7884, TotalMatchLoose = 2409, TotalMatchWin = 5475 } });
        result.Add(new Hero { PlayerId = 11, NickName = "Leris", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 14377, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 14676, TotalMatchPlayed = 1468, TotalMatchLoose = 810, TotalMatchWin = 658 } });
        result.Add(new Hero { PlayerId = 12, NickName = "Onion", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 14842, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 72472, TotalMatchPlayed = 7247, TotalMatchLoose = 5373, TotalMatchWin = 1874 } });
        result.Add(new Hero { PlayerId = 13, NickName = "Mordka", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 38520, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 138379, TotalMatchPlayed = 13838, TotalMatchLoose = 4566, TotalMatchWin = 9272 } });
        result.Add(new Hero { PlayerId = 14, NickName = "Kosmoter Mix", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 33591, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 123965, TotalMatchPlayed = 12397, TotalMatchLoose = 6032, TotalMatchWin = 6365 } });
        result.Add(new Hero { PlayerId = 15, NickName = "Kruuk", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 26553, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 61808, TotalMatchPlayed = 6181, TotalMatchLoose = 2911, TotalMatchWin = 3270 } });
        result.Add(new Hero { PlayerId = 16, NickName = "Qmag", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 43398, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 136300, TotalMatchPlayed = 13630, TotalMatchLoose = 5151, TotalMatchWin = 8479 } });
        result.Add(new Hero { PlayerId = 17, NickName = "Nartus", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 4143, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 72993, TotalMatchPlayed = 7299, TotalMatchLoose = 5306, TotalMatchWin = 1993 } });
        result.Add(new Hero { PlayerId = 18, NickName = "Berion", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 9404, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 139112, TotalMatchPlayed = 13911, TotalMatchLoose = 8572, TotalMatchWin = 5339 } });
        result.Add(new Hero { PlayerId = 19, NickName = "Leopold Staff", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 21823, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 91556, TotalMatchPlayed = 9156, TotalMatchLoose = 4702, TotalMatchWin = 4454 } });
        result.Add(new Hero { PlayerId = 20, NickName = "Mimosa", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 16040, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 31234, TotalMatchPlayed = 3123, TotalMatchLoose = 1801, TotalMatchWin = 1322 } });
        result.Add(new Hero { PlayerId = 21, NickName = "Grand Master", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 34495, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 19113, TotalMatchPlayed = 1911, TotalMatchLoose = 610, TotalMatchWin = 1301 } });
        result.Add(new Hero { PlayerId = 22, NickName = "Gandalf Szary", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 11425, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 27226, TotalMatchPlayed = 2723, TotalMatchLoose = 1654, TotalMatchWin = 1069 } });
        result.Add(new Hero { PlayerId = 23, NickName = "Priam", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 5329, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 2570, TotalMatchPlayed = 257, TotalMatchLoose = 130, TotalMatchWin = 127 } });
        result.Add(new Hero { PlayerId = 24, NickName = "Mefisto", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 38207, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 63841, TotalMatchPlayed = 6384, TotalMatchLoose = 4573, TotalMatchWin = 1811 } });
        result.Add(new Hero { PlayerId = 25, NickName = "NEO", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 18908, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58398, TotalMatchPlayed = 5840, TotalMatchLoose = 3381, TotalMatchWin = 2459 } });
        result.Add(new Hero { PlayerId = 26, NickName = "Morpheus", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 47686, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 112012, TotalMatchPlayed = 11201, TotalMatchLoose = 2967, TotalMatchWin = 8234 } });
        result.Add(new Hero { PlayerId = 27, NickName = "Gadzina", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 3241, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 12632, TotalMatchPlayed = 1263, TotalMatchLoose = 668, TotalMatchWin = 595 } });
        result.Add(new Hero { PlayerId = 28, NickName = "Rankorn", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 4892, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 65427, TotalMatchPlayed = 6543, TotalMatchLoose = 4018, TotalMatchWin = 2525 } });
        result.Add(new Hero { PlayerId = 29, NickName = "Harry Potter", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 1514, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 48745, TotalMatchPlayed = 4875, TotalMatchLoose = 2461, TotalMatchWin = 2414 } });
        result.Add(new Hero { PlayerId = 30, NickName = "Twoja Stara", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 31703, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 142066, TotalMatchPlayed = 14207, TotalMatchLoose = 6121, TotalMatchWin = 8086 } });
        result.Add(new Hero { PlayerId = 31, NickName = "Filius", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 39806, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 37583, TotalMatchPlayed = 3758, TotalMatchLoose = 1920, TotalMatchWin = 1838 } });
        result.Add(new Hero { PlayerId = 32, NickName = "Kamron", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 12048, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 36100, TotalMatchPlayed = 3610, TotalMatchLoose = 1602, TotalMatchWin = 2008 } });
        result.Add(new Hero { PlayerId = 33, NickName = "Domenor", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 45804, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 116964, TotalMatchPlayed = 11696, TotalMatchLoose = 8620, TotalMatchWin = 3076 } });
        result.Add(new Hero { PlayerId = 34, NickName = "Voldemort", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 47856, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 99021, TotalMatchPlayed = 9902, TotalMatchLoose = 5680, TotalMatchWin = 4222 } });
        result.Add(new Hero { PlayerId = 35, NickName = "Karakal", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 13416, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 30252, TotalMatchPlayed = 3025, TotalMatchLoose = 773, TotalMatchWin = 2252 } });
        result.Add(new Hero { PlayerId = 36, NickName = "Linkoln", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 6472, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 149516, TotalMatchPlayed = 14952, TotalMatchLoose = 9507, TotalMatchWin = 5445 } });
        result.Add(new Hero { PlayerId = 37, NickName = "Peroso Walzor", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 26043, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 87783, TotalMatchPlayed = 8778, TotalMatchLoose = 2549, TotalMatchWin = 6229 } });
        result.Add(new Hero { PlayerId = 38, NickName = "Qu Scalzus", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 44649, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 40802, TotalMatchPlayed = 4080, TotalMatchLoose = 2247, TotalMatchWin = 1833 } });
        result.Add(new Hero { PlayerId = 39, NickName = "Rhodan Horto", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 47095, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 61355, TotalMatchPlayed = 6136, TotalMatchLoose = 1843, TotalMatchWin = 4293 } });
        result.Add(new Hero { PlayerId = 40, NickName = "Haqus Gax", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 5593, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 86626, TotalMatchPlayed = 8663, TotalMatchLoose = 5976, TotalMatchWin = 2687 } });
        result.Add(new Hero { PlayerId = 41, NickName = "Zopium Xaxum", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 5288, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 136510, TotalMatchPlayed = 13651, TotalMatchLoose = 7257, TotalMatchWin = 6394 } });
        result.Add(new Hero { PlayerId = 42, NickName = "Ogondo Arqinzo", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 13951, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 87932, TotalMatchPlayed = 8793, TotalMatchLoose = 3201, TotalMatchWin = 5592 } });
        result.Add(new Hero { PlayerId = 43, NickName = "Gunnar", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 27593, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 98187, TotalMatchPlayed = 9819, TotalMatchLoose = 5915, TotalMatchWin = 3904 } });
        result.Add(new Hero { PlayerId = 44, NickName = "Lunar", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 7547, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58935, TotalMatchPlayed = 5894, TotalMatchLoose = 2744, TotalMatchWin = 3150 } });
        result.Add(new Hero { PlayerId = 45, NickName = "Ereus", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 47916, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 55188, TotalMatchPlayed = 5519, TotalMatchLoose = 3891, TotalMatchWin = 1628 } });
        result.Add(new Hero { PlayerId = 46, NickName = "Meriedon", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 37699, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 5074, TotalMatchPlayed = 507, TotalMatchLoose = 296, TotalMatchWin = 211 } });
        result.Add(new Hero { PlayerId = 47, NickName = "Kolendra", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 12833, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 86708, TotalMatchPlayed = 8671, TotalMatchLoose = 3003, TotalMatchWin = 5668 } });
        result.Add(new Hero { PlayerId = 48, NickName = "Brutus", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 11419, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 149165, TotalMatchPlayed = 14917, TotalMatchLoose = 7520, TotalMatchWin = 7397 } });
        result.Add(new Hero { PlayerId = 49, NickName = "Korneliusz", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 32486, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 26116, TotalMatchPlayed = 2612, TotalMatchLoose = 1457, TotalMatchWin = 1155 } });
        result.Add(new Hero { PlayerId = 50, NickName = "Albus Dumbledore", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 27588, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 73159, TotalMatchPlayed = 7316, TotalMatchLoose = 4718, TotalMatchWin = 2598 } });
        result.Add(new Hero { PlayerId = 51, NickName = "Levenstine", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 7844, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 125876, TotalMatchPlayed = 12588, TotalMatchLoose = 8464, TotalMatchWin = 4124 } });
        result.Add(new Hero { PlayerId = 52, NickName = "Markus", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 5095, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 120840, TotalMatchPlayed = 12084, TotalMatchLoose = 7325, TotalMatchWin = 4759 } });
        result.Add(new Hero { PlayerId = 53, NickName = "Kopernik", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 29493, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 80961, TotalMatchPlayed = 8096, TotalMatchLoose = 4795, TotalMatchWin = 3301 } });
        result.Add(new Hero { PlayerId = 54, NickName = "Lewandowski", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 8955, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 67567, TotalMatchPlayed = 6757, TotalMatchLoose = 2004, TotalMatchWin = 4753 } });
        result.Add(new Hero { PlayerId = 55, NickName = "Qwapos Platinah", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 499, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 102276, TotalMatchPlayed = 10228, TotalMatchLoose = 3280, TotalMatchWin = 6948 } });
        result.Add(new Hero { PlayerId = 56, NickName = "Horgellion Zuana", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 27666, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 17473, TotalMatchPlayed = 1747, TotalMatchLoose = 1045, TotalMatchWin = 702 } });
        result.Add(new Hero { PlayerId = 57, NickName = "Zaedicus", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 47684, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 105593, TotalMatchPlayed = 10559, TotalMatchLoose = 2848, TotalMatchWin = 7711 } });
        result.Add(new Hero { PlayerId = 58, NickName = "Zulion", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 37530, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 11204, TotalMatchPlayed = 1120, TotalMatchLoose = 603, TotalMatchWin = 517 } });
        result.Add(new Hero { PlayerId = 59, NickName = "Celebrimbor", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 35306, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 8206, TotalMatchPlayed = 821, TotalMatchLoose = 574, TotalMatchWin = 247 } });
        result.Add(new Hero { PlayerId = 60, NickName = "Maelstan Wuarto", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 6622, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 142669, TotalMatchPlayed = 14267, TotalMatchLoose = 9327, TotalMatchWin = 4940 } });
        result.Add(new Hero { PlayerId = 61, NickName = "Soren Anfarqo", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 39792, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 2497, TotalMatchPlayed = 250, TotalMatchLoose = 156, TotalMatchWin = 94 } });
        result.Add(new Hero { PlayerId = 62, NickName = "Praxtoner Mzanga", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 35348, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 122860, TotalMatchPlayed = 12286, TotalMatchLoose = 8205, TotalMatchWin = 4081 } });
        result.Add(new Hero { PlayerId = 63, NickName = "Oren Noor", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 12672, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 104003, TotalMatchPlayed = 10400, TotalMatchLoose = 3681, TotalMatchWin = 6719 } });
        result.Add(new Hero { PlayerId = 64, NickName = "Jael Azim", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 16447, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 12313, TotalMatchPlayed = 1231, TotalMatchLoose = 556, TotalMatchWin = 675 } });
        result.Add(new Hero { PlayerId = 65, NickName = "Nusair Zev", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 32707, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 79070, TotalMatchPlayed = 7907, TotalMatchLoose = 4849, TotalMatchWin = 3058 } });
        result.Add(new Hero { PlayerId = 66, NickName = "Segel Kivi", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 39563, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 60007, TotalMatchPlayed = 6001, TotalMatchLoose = 2754, TotalMatchWin = 3247 } });
        result.Add(new Hero { PlayerId = 67, NickName = "Zarif Akim", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 43568, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 33564, TotalMatchPlayed = 3356, TotalMatchLoose = 1570, TotalMatchWin = 1786 } });
        result.Add(new Hero { PlayerId = 68, NickName = "Anas Mazhar", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 14075, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 46990, TotalMatchPlayed = 4699, TotalMatchLoose = 1743, TotalMatchWin = 2956 } });
        result.Add(new Hero { PlayerId = 69, NickName = "Azhar Miksa", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 46078, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 84717, TotalMatchPlayed = 8472, TotalMatchLoose = 5468, TotalMatchWin = 3004 } });
        result.Add(new Hero { PlayerId = 70, NickName = "Amadi Jarib", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 39867, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58990, TotalMatchPlayed = 5899, TotalMatchLoose = 2025, TotalMatchWin = 3874 } });
        result.Add(new Hero { PlayerId = 71, NickName = "Glum Redpike", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 34189, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 67298, TotalMatchPlayed = 6730, TotalMatchLoose = 2371, TotalMatchWin = 4359 } });
        result.Add(new Hero { PlayerId = 72, NickName = "Ulf Froghead", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 28184, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 143238, TotalMatchPlayed = 14324, TotalMatchLoose = 5574, TotalMatchWin = 8750 } });
        result.Add(new Hero { PlayerId = 73, NickName = "Musa Khurram", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 6695, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 135019, TotalMatchPlayed = 13502, TotalMatchLoose = 4066, TotalMatchWin = 9436 } });
        result.Add(new Hero { PlayerId = 74, NickName = "Fox Yrresson", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 36346, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 56477, TotalMatchPlayed = 5648, TotalMatchLoose = 1992, TotalMatchWin = 3656 } });
        result.Add(new Hero { PlayerId = 75, NickName = "Uni the Pike", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 17338, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 73086, TotalMatchPlayed = 7309, TotalMatchLoose = 3475, TotalMatchWin = 3834 } });
        result.Add(new Hero { PlayerId = 76, NickName = "Sahir Nailah", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 9217, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 145404, TotalMatchPlayed = 14540, TotalMatchLoose = 8958, TotalMatchWin = 5582 } });
        result.Add(new Hero { PlayerId = 77, NickName = "Oxa the Rogue", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 30599, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 10962, TotalMatchPlayed = 1096, TotalMatchLoose = 458, TotalMatchWin = 638 } });
        result.Add(new Hero { PlayerId = 78, NickName = "Jaleel Haroun", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 34141, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 123237, TotalMatchPlayed = 12324, TotalMatchLoose = 3726, TotalMatchWin = 8598 } });
        result.Add(new Hero { PlayerId = 79, NickName = "Pyotr Yurikov", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 152, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 129972, TotalMatchPlayed = 12997, TotalMatchLoose = 3674, TotalMatchWin = 9323 } });
        result.Add(new Hero { PlayerId = 80, NickName = "Jasha Yashaov", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 24013, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 69567, TotalMatchPlayed = 6957, TotalMatchLoose = 2761, TotalMatchWin = 4196 } });
        result.Add(new Hero { PlayerId = 81, NickName = "Lar Haligsson", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 22529, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 122252, TotalMatchPlayed = 12225, TotalMatchLoose = 4487, TotalMatchWin = 7738 } });
        result.Add(new Hero { PlayerId = 82, NickName = "Mahmood Tibon", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 18503, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 145212, TotalMatchPlayed = 14521, TotalMatchLoose = 5272, TotalMatchWin = 9249 } });
        result.Add(new Hero { PlayerId = 83, NickName = "Oxa Redhammer", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 16015, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 143053, TotalMatchPlayed = 14305, TotalMatchLoose = 8466, TotalMatchWin = 5839 } });
        result.Add(new Hero { PlayerId = 84, NickName = "Boris the Rat", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 15658, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 55352, TotalMatchPlayed = 5535, TotalMatchLoose = 3758, TotalMatchWin = 1777 } });
        result.Add(new Hero { PlayerId = 85, NickName = "Yael Jamshaid", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 13232, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 73473, TotalMatchPlayed = 7347, TotalMatchLoose = 3446, TotalMatchWin = 3901 } });
        result.Add(new Hero { PlayerId = 86, NickName = "Lar Cedarwood", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 889, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 118186, TotalMatchPlayed = 11819, TotalMatchLoose = 5701, TotalMatchWin = 6118 } });
        result.Add(new Hero { PlayerId = 87, NickName = "Tellan Elmhome", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 12305, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 11123, TotalMatchPlayed = 1112, TotalMatchLoose = 317, TotalMatchWin = 795 } });
        result.Add(new Hero { PlayerId = 88, NickName = "Svein Grayring", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 37890, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 39347, TotalMatchPlayed = 3935, TotalMatchLoose = 1174, TotalMatchWin = 2761 } });
        result.Add(new Hero { PlayerId = 89, NickName = "Tosya of Livny", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 34349, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 24768, TotalMatchPlayed = 2477, TotalMatchLoose = 1021, TotalMatchWin = 1456 } });
        result.Add(new Hero { PlayerId = 90, NickName = "Arman Vladikov", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 46115, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 129404, TotalMatchPlayed = 12940, TotalMatchLoose = 7377, TotalMatchWin = 5563 } });
        result.Add(new Hero { PlayerId = 91, NickName = "Synn Goldwater", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 20799, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 24908, TotalMatchPlayed = 2491, TotalMatchLoose = 985, TotalMatchWin = 1506 } });
        result.Add(new Hero { PlayerId = 92, NickName = "Scur Alderhome", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 20024, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 120394, TotalMatchPlayed = 12039, TotalMatchLoose = 8727, TotalMatchWin = 3312 } });
        result.Add(new Hero { PlayerId = 93, NickName = "Ketil the Pike", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 29393, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 129853, TotalMatchPlayed = 12985, TotalMatchLoose = 9165, TotalMatchWin = 3820 } });
        result.Add(new Hero { PlayerId = 94, NickName = "Odd the Dagger", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 4945, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 28512, TotalMatchPlayed = 2851, TotalMatchLoose = 1086, TotalMatchWin = 1765 } });
        result.Add(new Hero { PlayerId = 95, NickName = "Osric Oakgrove", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 7296, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 82744, TotalMatchPlayed = 8274, TotalMatchLoose = 3372, TotalMatchWin = 4902 } });
        result.Add(new Hero { PlayerId = 96, NickName = "Zivon the Bear", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 24310, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 110278, TotalMatchPlayed = 11028, TotalMatchLoose = 7335, TotalMatchWin = 3693 } });
        result.Add(new Hero { PlayerId = 97, NickName = "Ofeig Bluehelm", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 43330, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 105995, TotalMatchPlayed = 10600, TotalMatchLoose = 4882, TotalMatchWin = 5718 } });
        result.Add(new Hero { PlayerId = 98, NickName = "Ozur Bluearrow", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 46450, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 121289, TotalMatchPlayed = 12129, TotalMatchLoose = 6309, TotalMatchWin = 5820 } });
        result.Add(new Hero { PlayerId = 99, NickName = "Ivar the Knife", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 47267, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 132205, TotalMatchPlayed = 13221, TotalMatchLoose = 5068, TotalMatchWin = 8153 } });
        result.Add(new Hero { PlayerId = 100, NickName = "Isen Elderleaf", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 23858, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 31680, TotalMatchPlayed = 3168, TotalMatchLoose = 1606, TotalMatchWin = 1562 } });
        result.Add(new Hero { PlayerId = 101, NickName = "Hroald Pighead", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 21033, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 49317, TotalMatchPlayed = 4932, TotalMatchLoose = 2461, TotalMatchWin = 2471 } });
        result.Add(new Hero { PlayerId = 102, NickName = "Borya the Hare", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 5724, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 67122, TotalMatchPlayed = 6712, TotalMatchLoose = 3019, TotalMatchWin = 3693 } });
        result.Add(new Hero { PlayerId = 103, NickName = "Modig Greenmark", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 2100, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 20775, TotalMatchPlayed = 2078, TotalMatchLoose = 838, TotalMatchWin = 1240 } });
        result.Add(new Hero { PlayerId = 104, NickName = "Gerhard Darkeye", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 15490, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 40497, TotalMatchPlayed = 4050, TotalMatchLoose = 1256, TotalMatchWin = 2794 } });
        result.Add(new Hero { PlayerId = 105, NickName = "Anhaga Birchson", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 20631, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 120428, TotalMatchPlayed = 12043, TotalMatchLoose = 5727, TotalMatchWin = 6316 } });
        result.Add(new Hero { PlayerId = 6, NickName = "Edlin Fireblade", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 46370, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 20677, TotalMatchPlayed = 2068, TotalMatchLoose = 1089, TotalMatchWin = 979 } });
        result.Add(new Hero { PlayerId = 64, NickName = "Motya the Snake", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 3522, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58948, TotalMatchPlayed = 5895, TotalMatchLoose = 3852, TotalMatchWin = 2043 } });
        result.Add(new Hero { PlayerId = 100, NickName = "Reule Wilyhands", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 47033, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 25141, TotalMatchPlayed = 2514, TotalMatchLoose = 999, TotalMatchWin = 1515 } });
        result.Add(new Hero { PlayerId = 92, NickName = "Wregan Ormodson", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 44751, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 16474, TotalMatchPlayed = 1647, TotalMatchLoose = 1233, TotalMatchWin = 414 } });
        result.Add(new Hero { PlayerId = 23, NickName = "Soren Greenseed", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 33472, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 19317, TotalMatchPlayed = 1932, TotalMatchLoose = 1191, TotalMatchWin = 741 } });
        result.Add(new Hero { PlayerId = 35, NickName = "Geir Strongpike", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 19842, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 20159, TotalMatchPlayed = 2016, TotalMatchLoose = 997, TotalMatchWin = 1019 } });
        result.Add(new Hero { PlayerId = 28, NickName = "Tellan Crocfoot", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 19471, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 119798, TotalMatchPlayed = 11980, TotalMatchLoose = 4042, TotalMatchWin = 7938 } });
        result.Add(new Hero { PlayerId = 52, NickName = "Modig Bluestaff", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 34711, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 53805, TotalMatchPlayed = 5381, TotalMatchLoose = 2666, TotalMatchWin = 2715 } });
        result.Add(new Hero { PlayerId = 21, NickName = "Valerik Levkaov", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 32400, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 34324, TotalMatchPlayed = 3432, TotalMatchLoose = 984, TotalMatchWin = 2448 } });
        result.Add(new Hero { PlayerId = 10, NickName = "Warian Oakgrove", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 44436, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 21850, TotalMatchPlayed = 2185, TotalMatchLoose = 682, TotalMatchWin = 1503 } });
        result.Add(new Hero { PlayerId = 58, NickName = "Yngvar Oaklance", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 43395, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 12315, TotalMatchPlayed = 1232, TotalMatchLoose = 733, TotalMatchWin = 499 } });
        result.Add(new Hero { PlayerId = 66, NickName = "Attor Eldergold", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 21851, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 108371, TotalMatchPlayed = 10837, TotalMatchLoose = 7140, TotalMatchWin = 3697 } });
        result.Add(new Hero { PlayerId = 43, NickName = "Thorir Jadehelm", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 36945, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 49141, TotalMatchPlayed = 4914, TotalMatchLoose = 1956, TotalMatchWin = 2958 } });
        result.Add(new Hero { PlayerId = 95, NickName = "Illugi the Deer", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 26164, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 114450, TotalMatchPlayed = 11445, TotalMatchLoose = 6178, TotalMatchWin = 5267 } });
        result.Add(new Hero { PlayerId = 61, NickName = "Modig Moonstone", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 33583, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 54245, TotalMatchPlayed = 5425, TotalMatchLoose = 4011, TotalMatchWin = 1414 } });
        result.Add(new Hero { PlayerId = 52, NickName = "Botolf Oaksaber", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 35611, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 23612, TotalMatchPlayed = 2361, TotalMatchLoose = 1600, TotalMatchWin = 761 } });
        result.Add(new Hero { PlayerId = 31, NickName = "Vladik of Ozhsk", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 20469, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 10500, TotalMatchPlayed = 1050, TotalMatchLoose = 335, TotalMatchWin = 715 } });
        result.Add(new Hero { PlayerId = 100, NickName = "Stefan the Rock", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 20553, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 9063, TotalMatchPlayed = 906, TotalMatchLoose = 451, TotalMatchWin = 455 } });
        result.Add(new Hero { PlayerId = 24, NickName = "Egor the Lizard", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 47452, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 115969, TotalMatchPlayed = 11597, TotalMatchLoose = 6767, TotalMatchWin = 4830 } });
        result.Add(new Hero { PlayerId = 79, NickName = "Lukyan the Tall", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 15140, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 110589, TotalMatchPlayed = 11059, TotalMatchLoose = 5643, TotalMatchWin = 5416 } });
        result.Add(new Hero { PlayerId = 54, NickName = "Hogni Dinohunter", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 27270, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 30688, TotalMatchPlayed = 3069, TotalMatchLoose = 2089, TotalMatchWin = 980 } });
        result.Add(new Hero { PlayerId = 90, NickName = "Edlin Maccussson", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 36152, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 138939, TotalMatchPlayed = 13894, TotalMatchLoose = 4839, TotalMatchWin = 9055 } });
        result.Add(new Hero { PlayerId = 72, NickName = "Ivar Crowtrapper", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 9681, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 141187, TotalMatchPlayed = 14119, TotalMatchLoose = 9894, TotalMatchWin = 4225 } });
        result.Add(new Hero { PlayerId = 47, NickName = "Yakov the Badger", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 17892, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 2041, TotalMatchPlayed = 204, TotalMatchLoose = 56, TotalMatchWin = 148 } });
        result.Add(new Hero { PlayerId = 54, NickName = "Rheged Galansson", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 40766, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 122963, TotalMatchPlayed = 12296, TotalMatchLoose = 8784, TotalMatchWin = 3512 } });
        result.Add(new Hero { PlayerId = 15, NickName = "Halvard Moonfish", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 35337, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 41991, TotalMatchPlayed = 4199, TotalMatchLoose = 1795, TotalMatchWin = 2404 } });
        result.Add(new Hero { PlayerId = 11, NickName = "Oxa Diamondstaff", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 37777, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 27817, TotalMatchPlayed = 2782, TotalMatchLoose = 1433, TotalMatchWin = 1349 } });
        result.Add(new Hero { PlayerId = 35, NickName = "Snorri Graylance", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 30075, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 59810, TotalMatchPlayed = 5981, TotalMatchLoose = 1556, TotalMatchWin = 4425 } });
        result.Add(new Hero { PlayerId = 11, NickName = "Mikhail the Deer", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 15304, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58298, TotalMatchPlayed = 5830, TotalMatchLoose = 2907, TotalMatchWin = 2923 } });
        result.Add(new Hero { PlayerId = 91, NickName = "Karolek of Duben", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 8664, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 112600, TotalMatchPlayed = 11260, TotalMatchLoose = 6474, TotalMatchWin = 4786 } });
        result.Add(new Hero { PlayerId = 30, NickName = "Strang Firelance", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 692, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 4842, TotalMatchPlayed = 484, TotalMatchLoose = 262, TotalMatchWin = 222 } });
        result.Add(new Hero { PlayerId = 97, NickName = "Deogol Cedarleaf", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 13151, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 22072, TotalMatchPlayed = 2207, TotalMatchLoose = 773, TotalMatchWin = 1434 } });
        result.Add(new Hero { PlayerId = 37, NickName = "Kiril Valerikski", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 10762, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 134284, TotalMatchPlayed = 13428, TotalMatchLoose = 5507, TotalMatchWin = 7921 } });
        result.Add(new Hero { PlayerId = 92, NickName = "Finn Macewielder", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 30243, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 143774, TotalMatchPlayed = 14377, TotalMatchLoose = 4278, TotalMatchWin = 10099 } });
        result.Add(new Hero { PlayerId = 97, NickName = "Ormod Brogansson", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 22531, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 27031, TotalMatchPlayed = 2703, TotalMatchLoose = 989, TotalMatchWin = 1714 } });
        result.Add(new Hero { PlayerId = 77, NickName = "Kenric Bloodclub", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 25866, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 99858, TotalMatchPlayed = 9986, TotalMatchLoose = 4447, TotalMatchWin = 5539 } });
        result.Add(new Hero { PlayerId = 62, NickName = "Lar Bronzedagger", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 20117, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 77363, TotalMatchPlayed = 7736, TotalMatchLoose = 2224, TotalMatchWin = 5512 } });
        result.Add(new Hero { PlayerId = 96, NickName = "Lizard Tellanson", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 37430, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 18901, TotalMatchPlayed = 1890, TotalMatchLoose = 588, TotalMatchWin = 1302 } });
        result.Add(new Hero { PlayerId = 18, NickName = "Thorgils the Axe", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 25720, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 140212, TotalMatchPlayed = 14021, TotalMatchLoose = 8112, TotalMatchWin = 5909 } });
        result.Add(new Hero { PlayerId = 91, NickName = "Thorhall Oakmark", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 12369, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 127046, TotalMatchPlayed = 12705, TotalMatchLoose = 3910, TotalMatchWin = 8795 } });
        result.Add(new Hero { PlayerId = 42, NickName = "Soren Yellowbird", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 1151, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 134598, TotalMatchPlayed = 13460, TotalMatchLoose = 7963, TotalMatchWin = 5497 } });
        result.Add(new Hero { PlayerId = 8, NickName = "Lar Lancebreaker", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 126, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 85918, TotalMatchPlayed = 8592, TotalMatchLoose = 5670, TotalMatchWin = 2922 } });
        result.Add(new Hero { PlayerId = 11, NickName = "Runolf Ofeigssen", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 2075, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 80962, TotalMatchPlayed = 8096, TotalMatchLoose = 5458, TotalMatchWin = 2638 } });
        result.Add(new Hero { PlayerId = 74, NickName = "Gaderian Oxasson", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 14472, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 47460, TotalMatchPlayed = 4746, TotalMatchLoose = 1875, TotalMatchWin = 2871 } });
        result.Add(new Hero { PlayerId = 7, NickName = "Sighvat the Goat", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 27565, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 141035, TotalMatchPlayed = 14104, TotalMatchLoose = 3530, TotalMatchWin = 10574 } });
        result.Add(new Hero { PlayerId = 32, NickName = "Onund the Monkey", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 17327, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 41893, TotalMatchPlayed = 4189, TotalMatchLoose = 1667, TotalMatchWin = 2522 } });
        result.Add(new Hero { PlayerId = 87, NickName = "Stefan Dimitriov", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 46369, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 136881, TotalMatchPlayed = 13688, TotalMatchLoose = 6145, TotalMatchWin = 7543 } });
        result.Add(new Hero { PlayerId = 80, NickName = "Solvi the Monkey", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 36284, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 125645, TotalMatchPlayed = 12565, TotalMatchLoose = 8603, TotalMatchWin = 3962 } });
        result.Add(new Hero { PlayerId = 38, NickName = "Eyjolf Goatherder", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 15680, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 51057, TotalMatchPlayed = 5106, TotalMatchLoose = 1513, TotalMatchWin = 3593 } });
        result.Add(new Hero { PlayerId = 47, NickName = "Michel Slightcuts", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 20879, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 131076, TotalMatchPlayed = 13108, TotalMatchLoose = 9717, TotalMatchWin = 3391 } });
        result.Add(new Hero { PlayerId = 32, NickName = "Hjalti Goldshield", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 7529, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 141422, TotalMatchPlayed = 14142, TotalMatchLoose = 7423, TotalMatchWin = 6719 } });
        result.Add(new Hero { PlayerId = 71, NickName = "Fredek the Hermit", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 29328, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 32378, TotalMatchPlayed = 3238, TotalMatchLoose = 2319, TotalMatchWin = 919 } });
        result.Add(new Hero { PlayerId = 34, NickName = "Hardouin Silkcuts", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 29732, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 34260, TotalMatchPlayed = 3426, TotalMatchLoose = 1284, TotalMatchWin = 2142 } });
        result.Add(new Hero { PlayerId = 89, NickName = "Torr Staffthrower", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 17360, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 131480, TotalMatchPlayed = 13148, TotalMatchLoose = 9293, TotalMatchWin = 3855 } });
        result.Add(new Hero { PlayerId = 84, NickName = "Odon the Torturer", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 4715, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 27424, TotalMatchPlayed = 2742, TotalMatchLoose = 751, TotalMatchWin = 1991 } });
        result.Add(new Hero { PlayerId = 56, NickName = "Penrith Aldredson", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 49285, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 141498, TotalMatchPlayed = 14150, TotalMatchLoose = 5763, TotalMatchWin = 8387 } });
        result.Add(new Hero { PlayerId = 7, NickName = "Valerik the Tiger", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 22276, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 94644, TotalMatchPlayed = 9464, TotalMatchLoose = 4096, TotalMatchWin = 5368 } });
        result.Add(new Hero { PlayerId = 40, NickName = "Demon Awierganson", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 41446, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 20494, TotalMatchPlayed = 2049, TotalMatchLoose = 1375, TotalMatchWin = 674 } });
        result.Add(new Hero { PlayerId = 56, NickName = "Konrad Whitestone", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 46598, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 49578, TotalMatchPlayed = 4958, TotalMatchLoose = 2845, TotalMatchWin = 2113 } });
        result.Add(new Hero { PlayerId = 98, NickName = "Sigmund Bronzeaxe", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 36691, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 124479, TotalMatchPlayed = 12448, TotalMatchLoose = 9232, TotalMatchWin = 3216 } });
        result.Add(new Hero { PlayerId = 13, NickName = "Ketil Pikewielder", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 27913, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 10602, TotalMatchPlayed = 1060, TotalMatchLoose = 473, TotalMatchWin = 587 } });
        result.Add(new Hero { PlayerId = 48, NickName = "Aldhelm Starblade", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 2100, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 90342, TotalMatchPlayed = 9034, TotalMatchLoose = 5953, TotalMatchWin = 3081 } });
        result.Add(new Hero { PlayerId = 12, NickName = "Tamar Diamondmace", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 19202, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 42604, TotalMatchPlayed = 4260, TotalMatchLoose = 2286, TotalMatchWin = 1974 } });
        result.Add(new Hero { PlayerId = 82, NickName = "Vasilii the Shark", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 48398, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 74895, TotalMatchPlayed = 7490, TotalMatchLoose = 2068, TotalMatchWin = 5422 } });
        result.Add(new Hero { PlayerId = 40, NickName = "Besyrwan Jadehelm", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 642, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 139104, TotalMatchPlayed = 13910, TotalMatchLoose = 4368, TotalMatchWin = 9542 } });
        result.Add(new Hero { PlayerId = 40, NickName = "Adrik the Bastard", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 12605, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 48797, TotalMatchPlayed = 4880, TotalMatchLoose = 1785, TotalMatchWin = 3095 } });
        result.Add(new Hero { PlayerId = 7, NickName = "Edlin Snakerunner", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 23356, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 64040, TotalMatchPlayed = 6404, TotalMatchLoose = 2999, TotalMatchWin = 3405 } });
        result.Add(new Hero { PlayerId = 73, NickName = "Zivon the Grizzly", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 20828, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 35571, TotalMatchPlayed = 3557, TotalMatchLoose = 1517, TotalMatchWin = 2040 } });
        result.Add(new Hero { PlayerId = 81, NickName = "Thorgeir the Mace", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 38426, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 57226, TotalMatchPlayed = 5723, TotalMatchLoose = 1652, TotalMatchWin = 4071 } });
        result.Add(new Hero { PlayerId = 52, NickName = "Deogol Wyrmseeker", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 13762, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 95930, TotalMatchPlayed = 9593, TotalMatchLoose = 2433, TotalMatchWin = 7160 } });
        result.Add(new Hero { PlayerId = 91, NickName = "Yakov the Bastard", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 35343, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58675, TotalMatchPlayed = 5868, TotalMatchLoose = 3914, TotalMatchWin = 1954 } });
        result.Add(new Hero { PlayerId = 64, NickName = "Ivan of Verkhovsk", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 6686, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 104581, TotalMatchPlayed = 10458, TotalMatchLoose = 5381, TotalMatchWin = 5077 } });
        result.Add(new Hero { PlayerId = 57, NickName = "Eldgrim the Saber", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 5227, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 34703, TotalMatchPlayed = 3470, TotalMatchLoose = 1817, TotalMatchWin = 1653 } });
        result.Add(new Hero { PlayerId = 17, NickName = "Eystein Ironknife", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 959, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 23682, TotalMatchPlayed = 2368, TotalMatchLoose = 887, TotalMatchWin = 1481 } });
        result.Add(new Hero { PlayerId = 42, NickName = "Snorri Greenarrow", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 9794, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 135915, TotalMatchPlayed = 13592, TotalMatchLoose = 8571, TotalMatchWin = 5021 } });
        result.Add(new Hero { PlayerId = 19, NickName = "Botolf the Cougar", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 23599, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 4308, TotalMatchPlayed = 431, TotalMatchLoose = 192, TotalMatchWin = 239 } });
        result.Add(new Hero { PlayerId = 26, NickName = "Jasha the Panther", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 30542, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 109971, TotalMatchPlayed = 10997, TotalMatchLoose = 5490, TotalMatchWin = 5507 } });
        result.Add(new Hero { PlayerId = 92, NickName = "Sarlic Dinokiller", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 28982, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 58139, TotalMatchPlayed = 5814, TotalMatchLoose = 3238, TotalMatchWin = 2576 } });
        result.Add(new Hero { PlayerId = 83, NickName = "Fadeyka the Blind", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 11128, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 60153, TotalMatchPlayed = 6015, TotalMatchLoose = 2024, TotalMatchWin = 3991 } });
        result.Add(new Hero { PlayerId = 73, NickName = "Eyjolf Wyrmrunner", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 37876, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 148473, TotalMatchPlayed = 14847, TotalMatchLoose = 8651, TotalMatchWin = 6196 } });
        result.Add(new Hero { PlayerId = 28, NickName = "Finnbogi the Wyrm", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 15668, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 140704, TotalMatchPlayed = 14070, TotalMatchLoose = 9698, TotalMatchWin = 4372 } });
        result.Add(new Hero { PlayerId = 81, NickName = "Acennan Hardstone", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 41351, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 60144, TotalMatchPlayed = 6014, TotalMatchLoose = 3412, TotalMatchWin = 2602 } });
        result.Add(new Hero { PlayerId = 40, NickName = "Yngve Littleearth", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 828, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 11864, TotalMatchPlayed = 1186, TotalMatchLoose = 759, TotalMatchWin = 427 } });
        result.Add(new Hero { PlayerId = 10, NickName = "Tosya the Wayfarer", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 1813, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 69808, TotalMatchPlayed = 6981, TotalMatchLoose = 5227, TotalMatchWin = 1754 } });
        result.Add(new Hero { PlayerId = 62, NickName = "Avenal Nimblemover", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 27381, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 79307, TotalMatchPlayed = 7931, TotalMatchLoose = 3925, TotalMatchWin = 4006 } });
        result.Add(new Hero { PlayerId = 69, NickName = "Thorgils Dinotooth", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 49142, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 113942, TotalMatchPlayed = 11394, TotalMatchLoose = 6020, TotalMatchWin = 5374 } });
        result.Add(new Hero { PlayerId = 81, NickName = "Sergei Lukyanovich", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 24884, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 63109, TotalMatchPlayed = 6311, TotalMatchLoose = 4468, TotalMatchWin = 1843 } });
        result.Add(new Hero { PlayerId = 65, NickName = "Aart Arrowthruster", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 10659, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 44871, TotalMatchPlayed = 4487, TotalMatchLoose = 1681, TotalMatchWin = 2806 } });
        result.Add(new Hero { PlayerId = 50, NickName = "Ottar Gunnlaugsson", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 37523, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 82165, TotalMatchPlayed = 8217, TotalMatchLoose = 2351, TotalMatchWin = 5866 } });
        result.Add(new Hero { PlayerId = 74, NickName = "Egil Spearthrasher", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 6908, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 122240, TotalMatchPlayed = 12224, TotalMatchLoose = 6543, TotalMatchWin = 5681 } });
        result.Add(new Hero { PlayerId = 59, NickName = "Bardi Spearwielder", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 5, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 131064, TotalMatchPlayed = 13106, TotalMatchLoose = 3858, TotalMatchWin = 9248 } });
        result.Add(new Hero { PlayerId = 66, NickName = "Lodin Staffthrower", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 45642, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 26319, TotalMatchPlayed = 2632, TotalMatchLoose = 1433, TotalMatchWin = 1199 } });
        result.Add(new Hero { PlayerId = 37, NickName = "Vladik Stefanovich", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 8485, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 10081, TotalMatchPlayed = 1008, TotalMatchLoose = 406, TotalMatchWin = 602 } });
        result.Add(new Hero { PlayerId = 56, NickName = "Ingjald Isleifsson", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 41333, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 38906, TotalMatchPlayed = 3891, TotalMatchLoose = 1524, TotalMatchWin = 2367 } });
        result.Add(new Hero { PlayerId = 27, NickName = "Aldred Eagleherder", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 28398, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 14307, TotalMatchPlayed = 1431, TotalMatchLoose = 519, TotalMatchWin = 912 } });
        result.Add(new Hero { PlayerId = 10, NickName = "Illugi Goatcatcher", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 35420, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 48096, TotalMatchPlayed = 4810, TotalMatchLoose = 1255, TotalMatchWin = 3555 } });
        result.Add(new Hero { PlayerId = 36, NickName = "Hallfred Hoghunter", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 32624, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 127621, TotalMatchPlayed = 12762, TotalMatchLoose = 5806, TotalMatchWin = 6956 } });
        result.Add(new Hero { PlayerId = 27, NickName = "Geirstein Blueclub", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 19570, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 12164, TotalMatchPlayed = 1216, TotalMatchLoose = 581, TotalMatchWin = 635 } });
        result.Add(new Hero { PlayerId = 40, NickName = "Rodor the Torturer", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 14355, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 25396, TotalMatchPlayed = 2540, TotalMatchLoose = 774, TotalMatchWin = 1766 } });
        result.Add(new Hero { PlayerId = 47, NickName = "Agramant Silkmover", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 30579, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 38659, TotalMatchPlayed = 3866, TotalMatchLoose = 2160, TotalMatchWin = 1706 } });
        result.Add(new Hero { PlayerId = 43, NickName = "Mikhail Vanechkaov", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 30564, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 123031, TotalMatchPlayed = 12303, TotalMatchLoose = 8473, TotalMatchWin = 3830 } });
        result.Add(new Hero { PlayerId = 27, NickName = "Bergthor the Staff", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 30762, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 21354, TotalMatchPlayed = 2135, TotalMatchLoose = 699, TotalMatchWin = 1436 } });
        result.Add(new Hero { PlayerId = 94, NickName = "Grindan Yellowworm", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 4443, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 5346, TotalMatchPlayed = 535, TotalMatchLoose = 227, TotalMatchWin = 308 } });
        result.Add(new Hero { PlayerId = 52, NickName = "Yngvar the Panther", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 45029, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 129389, TotalMatchPlayed = 12939, TotalMatchLoose = 3551, TotalMatchWin = 9388 } });
        result.Add(new Hero { PlayerId = 34, NickName = "Levka the Poisoner", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 25534, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 91845, TotalMatchPlayed = 9185, TotalMatchLoose = 6770, TotalMatchWin = 2415 } });
        result.Add(new Hero { PlayerId = 16, NickName = "Wregan Clubwielder", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 4912, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 21943, TotalMatchPlayed = 2194, TotalMatchLoose = 562, TotalMatchWin = 1632 } });
        result.Add(new Hero { PlayerId = 73, NickName = "Cadmon Banningsson", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 29736, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 87669, TotalMatchPlayed = 8767, TotalMatchLoose = 6032, TotalMatchWin = 2735 } });
        result.Add(new Hero { PlayerId = 34, NickName = "Hafgrim Styrkarsen", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 8887, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 43262, TotalMatchPlayed = 4326, TotalMatchLoose = 2401, TotalMatchWin = 1925 } });
        result.Add(new Hero { PlayerId = 49, NickName = "Ormod Govannonsson", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 36445, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 57944, TotalMatchPlayed = 5794, TotalMatchLoose = 2771, TotalMatchWin = 3023 } });
        result.Add(new Hero { PlayerId = 26, NickName = "Prasutagus Haligson", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 35951, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 38279, TotalMatchPlayed = 3828, TotalMatchLoose = 960, TotalMatchWin = 2868 } });
        result.Add(new Hero { PlayerId = 68, NickName = "Thorgrim Otryggssen", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 741, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 77312, TotalMatchPlayed = 7731, TotalMatchLoose = 4015, TotalMatchWin = 3716 } });
        result.Add(new Hero { PlayerId = 31, NickName = "Bertrand Tracehands", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 18056, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 5745, TotalMatchPlayed = 575, TotalMatchLoose = 155, TotalMatchWin = 420 } });
        result.Add(new Hero { PlayerId = 30, NickName = "Yrre the Millwright", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 24103, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 20606, TotalMatchPlayed = 2061, TotalMatchLoose = 968, TotalMatchWin = 1093 } });
        result.Add(new Hero { PlayerId = 73, NickName = "Arnfinn Beavertooth", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 7363, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 86130, TotalMatchPlayed = 8613, TotalMatchLoose = 6411, TotalMatchWin = 2202 } });
        result.Add(new Hero { PlayerId = 47, NickName = "Aart the Millwright", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 40497, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 147571, TotalMatchPlayed = 14757, TotalMatchLoose = 9256, TotalMatchWin = 5501 } });
        result.Add(new Hero { PlayerId = 30, NickName = "Geraint the Juggler", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 28867, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 39782, TotalMatchPlayed = 3978, TotalMatchLoose = 2168, TotalMatchWin = 1810 } });
        result.Add(new Hero { PlayerId = 6, NickName = "Sturla Saberbreaker", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 42083, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 26172, TotalMatchPlayed = 2617, TotalMatchLoose = 1370, TotalMatchWin = 1247 } });
        result.Add(new Hero { PlayerId = 18, NickName = "Geirstein the Staff", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 25939, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 100112, TotalMatchPlayed = 10011, TotalMatchLoose = 3466, TotalMatchWin = 6545 } });
        result.Add(new Hero { PlayerId = 27, NickName = "Gunnar Possumseeker", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 12153, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 66903, TotalMatchPlayed = 6690, TotalMatchLoose = 3407, TotalMatchWin = 3283 } });
        result.Add(new Hero { PlayerId = 58, NickName = "Hedin Thorbjornsson", AvatarImageNumber = 4, Profession = (HeroProfession)0, Gold = 11657, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 72131, TotalMatchPlayed = 7213, TotalMatchLoose = 4459, TotalMatchWin = 2754 } });
        result.Add(new Hero { PlayerId = 21, NickName = "Tamar the Fisherman", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 1478, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 42290, TotalMatchPlayed = 4229, TotalMatchLoose = 1061, TotalMatchWin = 3168 } });
        result.Add(new Hero { PlayerId = 55, NickName = "Rheged Whitemorning", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 26583, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 146236, TotalMatchPlayed = 14624, TotalMatchLoose = 8766, TotalMatchWin = 5858 } });
        result.Add(new Hero { PlayerId = 19, NickName = "Antinko Semyonovich", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 40029, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 7864, TotalMatchPlayed = 786, TotalMatchLoose = 480, TotalMatchWin = 306 } });
        result.Add(new Hero { PlayerId = 85, NickName = "Thorfinn Whitesword", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 35288, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 6988, TotalMatchPlayed = 699, TotalMatchLoose = 231, TotalMatchWin = 468 } });
        result.Add(new Hero { PlayerId = 54, NickName = "Athelstan Foxslayer", AvatarImageNumber = 2, Profession = (HeroProfession)0, Gold = 35553, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 116439, TotalMatchPlayed = 11644, TotalMatchLoose = 6626, TotalMatchWin = 5018 } });
        result.Add(new Hero { PlayerId = 92, NickName = "Mikhail the Leopard", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 11507, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 59454, TotalMatchPlayed = 5945, TotalMatchLoose = 3790, TotalMatchWin = 2155 } });
        result.Add(new Hero { PlayerId = 23, NickName = "Arnfinn Finnbogisen", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 39345, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 138627, TotalMatchPlayed = 13863, TotalMatchLoose = 9016, TotalMatchWin = 4847 } });
        result.Add(new Hero { PlayerId = 30, NickName = "Athelstan Faransson", AvatarImageNumber = 1, Profession = (HeroProfession)0, Gold = 40663, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 117400, TotalMatchPlayed = 11740, TotalMatchLoose = 7261, TotalMatchWin = 4479 } });
        result.Add(new Hero { PlayerId = 15, NickName = "Lucan the Mercenary", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 47122, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 68585, TotalMatchPlayed = 6859, TotalMatchLoose = 4110, TotalMatchWin = 2749 } });


        foreach (var hero in result)
        {
            hero.Inventory = new();
            hero.Inventory.Add(new HeroItem() { ItemId = rnd.Next(1, 15), InUse = true, ItemEndurance = rnd.Next(3000, 10000) / 100d });
            hero.Inventory.Add(new HeroItem() { ItemId = rnd.Next(16, 30), InUse = true, ItemEndurance = rnd.Next(7000, 10000) / 100d });
            hero.Inventory.Add(new HeroItem() { ItemId = rnd.Next(1, 15), InUse = false, ItemEndurance = rnd.Next(300, 2000) / 100d });

            var itemCount = rnd.Next(1, 7);

            for (int j = 1; j <= itemCount; j++)
            {
                hero.Inventory.Add(new HeroItem() { HeroId = hero.Id, ItemId = rnd.Next(1, 30), InUse = false, ItemEndurance = rnd.Next(500, 10000) / 100d });
            }
        }

        // Data for Admin and Moderator Users
        result.Add(new Hero { PlayerId = 1, NickName = "Saruman", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 150000, TotalMatchPlayed = 15000, TotalMatchLoose = 3000, TotalMatchWin = 12000 }, Inventory = GetAdminInventory(rnd) });
        result.Add(new Hero { PlayerId = 1, NickName = "Tester A", AvatarImageNumber = 7, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 100, TotalMatchPlayed = 10, TotalMatchLoose = 3, TotalMatchWin = 7 }, Inventory = GetBasicInventory() });
        result.Add(new Hero { PlayerId = 2, NickName = "Gandalf", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 150000, TotalMatchPlayed = 15000, TotalMatchLoose = 3000, TotalMatchWin = 12000 }, Inventory = GetAdminInventory(rnd) });
        result.Add(new Hero { PlayerId = 2, NickName = "Tester B", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 100, TotalMatchPlayed = 10, TotalMatchLoose = 3, TotalMatchWin = 7 }, Inventory = GetBasicInventory() });
        result.Add(new Hero { PlayerId = 3, NickName = "Dumbledore", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 150000, TotalMatchPlayed = 15000, TotalMatchLoose = 3000, TotalMatchWin = 12000 }, Inventory = GetAdminInventory(rnd) });
        result.Add(new Hero { PlayerId = 3, NickName = "Tester C", AvatarImageNumber = 6, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 100, TotalMatchPlayed = 10, TotalMatchLoose = 3, TotalMatchWin = 7 }, Inventory = GetBasicInventory() });
        result.Add(new Hero { PlayerId = 4, NickName = "Grindelwald", AvatarImageNumber = 3, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 150000, TotalMatchPlayed = 15000, TotalMatchLoose = 3000, TotalMatchWin = 12000 }, Inventory = GetAdminInventory(rnd) });
        result.Add(new Hero { PlayerId = 4, NickName = "Tester D", AvatarImageNumber = 5, Profession = (HeroProfession)0, Gold = 200000, Attributes = GetSorcerersAttr(), Statistics = new Statistics() { RankPoints = 100, TotalMatchPlayed = 10, TotalMatchLoose = 3, TotalMatchWin = 7 }, Inventory = GetBasicInventory() });
        result.Add(new Hero { PlayerId = 5, NickName = "Moderator A", AvatarImageNumber = 4, Profession = (HeroProfession)1, Gold = 1000000, Attributes = GetNecroAttr(), Statistics = new Statistics() { RankPoints = 0, TotalMatchPlayed = 0, TotalMatchLoose = 0, TotalMatchWin = 0 } });

        return result;
    }

    private HeroAttributes GetNecroAttr()
    {
        return new HeroAttributes() { DailyRewardEnergy = 10, Damage = 10, Precision = 0, Specialization = 5, MaxHealth = 25, CurrentHealth = 25, Defense = 0, Reflex = 0 };
    }
    private HeroAttributes GetSorcerersAttr()
    {
        return new HeroAttributes() { DailyRewardEnergy = 10, Damage = 10, Precision = 5, Specialization = 0, MaxHealth = 25, CurrentHealth = 25, Defense = 0, Reflex = 0 };
    }

    private List<HeroItem> GetAdminInventory(Random rnd)
    {
        var result = new List<HeroItem>();

        result.Add(new HeroItem() { ItemId = 5, InUse = true, ItemEndurance = 99.00d });
        result.Add(new HeroItem() { ItemId = 20, InUse = true, ItemEndurance = 74.53d });

        for (int i = 1; i <= 30; i++)
        {
            result.Add(new HeroItem() { ItemId = i, InUse = false, ItemEndurance = rnd.Next(500, 10000) / 100d });
        }

        return result;
    }

    private List<HeroItem> GetBasicInventory()
    {
        var result = new List<HeroItem>();

        result.Add(new HeroItem() { ItemId = 1, InUse = true, ItemEndurance = 100.00d });
        result.Add(new HeroItem() { ItemId = 16, InUse = true, ItemEndurance = 100.00d });
        result.Add(new HeroItem() { ItemId = 6, InUse = false, ItemEndurance = 100.00d });

        return result;
    }
}